<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Om programmas te kijken moet je ingelogd _4796e4</name>
   <tag></tag>
   <elementGuidId>0aee8f5e-d98a-4a07-8e8e-bd70917542c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal']/div/section/div/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.Bra-E</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>eb86441c-4731-4d5a-b534-de0de35dc043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Bra-E</value>
      <webElementGuid>4b609754-2169-4dc2-875a-0da6b30116f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Om programma’s te kijken moet je ingelogd zijn met je NLZIET-account.</value>
      <webElementGuid>ba535fee-f4ea-4117-9f4d-32612da45863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal&quot;)/div[@class=&quot;Yj-98&quot;]/section[@class=&quot;gYjx2 CSwyI&quot;]/div[@class=&quot;q6v9P&quot;]/div[@class=&quot;RtMZs&quot;]/p[@class=&quot;Bra-E&quot;]</value>
      <webElementGuid>d549dadb-5157-4b1a-bc57-6239eaa32edb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal']/div/section/div/div/p</value>
      <webElementGuid>ca9e96a7-ef30-47c8-a600-e1c8b6d3c9cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Je bent niet ingelogd'])[1]/following::p[1]</value>
      <webElementGuid>d3952cb6-cf78-4c43-84b0-7c80b5f68877</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lees hier welke browsers er worden ondersteund'])[1]/following::p[1]</value>
      <webElementGuid>ad6a8002-9f40-4bcb-a3b7-8fbe8e6ab307</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inloggen'])[1]/preceding::p[1]</value>
      <webElementGuid>59e48144-d8e8-447e-a83c-495851ff372e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nog geen account? Meld je aan.'])[1]/preceding::p[1]</value>
      <webElementGuid>9bcf3c19-2bf5-4e62-938b-d253959bca7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Om programma’s te kijken moet je ingelogd zijn met je NLZIET-account.']/parent::*</value>
      <webElementGuid>2e2ec146-f8db-49a7-84a8-27e32f091886</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/p</value>
      <webElementGuid>4150d7ce-0d41-433b-a05c-62e5b33b9777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Om programma’s te kijken moet je ingelogd zijn met je NLZIET-account.' or . = 'Om programma’s te kijken moet je ingelogd zijn met je NLZIET-account.')]</value>
      <webElementGuid>641c1713-20dc-4cde-9067-11c16a87872c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
