<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>1ste profiel</name>
   <tag></tag>
   <elementGuidId>6de0a410-e5f1-458d-9d42-d4ac5092ac52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Wie gaat er kijken?'])[1]/following::*[name()='svg'][1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>svg._5U1LB.jHl-o</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>1d6e3b93-cc04-4158-aa78-7d87229ccf80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>56</value>
      <webElementGuid>f0d2c57e-086d-4aa6-bfa1-0462ffc0f136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>56</value>
      <webElementGuid>a0217b69-cdea-402e-8aa4-6c0216be5556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 56 56</value>
      <webElementGuid>ddf5b76a-445c-4a36-87bb-85cdfddddd2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>3d773c13-a35a-4c66-9977-3bbfceb9de56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>56bd82ea-6318-406b-8321-0619c9a51507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_5U1LB jHl-o</value>
      <webElementGuid>ea4fc1f4-f5a6-49fe-96f1-5a8b2330c092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[1]/section[@class=&quot;n7wtA&quot;]/ul[@class=&quot;_2kY8F&quot;]/li[1]/button[@class=&quot;RPtvS&quot;]/div[@class=&quot;_5U1LB&quot;]/svg[@class=&quot;_5U1LB jHl-o&quot;]</value>
      <webElementGuid>f2e39781-0ea1-4205-9140-19f942256931</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wie gaat er kijken?'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>9edf2b42-0a48-4d6b-adf2-f95a905303b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lees hier welke browsers er worden ondersteund'])[1]/following::*[name()='svg'][2]</value>
      <webElementGuid>8179d4be-3391-4cd6-8bf6-96b12b299e9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Algemene voorwaarden'])[1]/preceding::*[name()='svg'][6]</value>
      <webElementGuid>d097194e-c656-48e9-a4aa-0cf85aff0486</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy &amp; cookies'])[1]/preceding::*[name()='svg'][6]</value>
      <webElementGuid>3fb2a811-d7d4-4f57-8586-89210f058b27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
