<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Algemene voorwaarden</name>
   <tag></tag>
   <elementGuidId>3d896b4c-f733-4012-bb6d-7bd653b56bce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.Dxzbt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/footer/div/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0ed1bfe0-b882-45f5-be69-58e0a028af43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Dxzbt</value>
      <webElementGuid>899e1379-2a66-4f22-b010-7f705cb9b1c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>6b558fa6-ea2d-4d10-9106-bd669ac2a5ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noreferrer</value>
      <webElementGuid>56f9895f-5fdc-44e5-bb21-107469d5b1d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.nlziet.nl/home/voorwaarden</value>
      <webElementGuid>a959a615-d74d-4202-bb60-09330a61e015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Algemene voorwaarden</value>
      <webElementGuid>2bf64752-f4eb-4099-9a02-57b0821ad3de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;oKpQ7&quot;]/footer[@class=&quot;GOdwA&quot;]/div[@class=&quot;fj-xB&quot;]/ul[@class=&quot;SC7OG&quot;]/li[@class=&quot;da4cg&quot;]/a[@class=&quot;Dxzbt&quot;]</value>
      <webElementGuid>b5ca8b2a-02db-40fc-b679-62908271a276</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/footer/div/ul/li/a</value>
      <webElementGuid>5fb55976-0d16-4c9d-9eae-1bc1e8f1c5c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Algemene voorwaarden')]</value>
      <webElementGuid>0f819cc1-8ab7-410b-ad2b-92392b1e1e8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toon alles'])[14]/following::a[2]</value>
      <webElementGuid>7015b794-3cc9-46b3-8cf0-be0aaf804a8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mr. Frank Visser: hoe is het nu met?'])[2]/following::a[3]</value>
      <webElementGuid>82c47831-fbd3-444f-b173-db14209d779d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy &amp; cookies'])[1]/preceding::a[1]</value>
      <webElementGuid>7abf87d0-e07f-41bc-8e18-70327fed6119</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hulp'])[1]/preceding::a[2]</value>
      <webElementGuid>17ea157a-4f74-4261-8d7b-330d71494462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Algemene voorwaarden']/parent::*</value>
      <webElementGuid>7d8a4923-3ed4-42cd-beb7-bf44028e8d04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.nlziet.nl/home/voorwaarden')]</value>
      <webElementGuid>6f6d5a9a-74ee-4293-8c09-591f8fb58d53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div/ul/li/a</value>
      <webElementGuid>8fba3288-8562-4f71-a958-e49d3bf3f12c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.nlziet.nl/home/voorwaarden' and (text() = 'Algemene voorwaarden' or . = 'Algemene voorwaarden')]</value>
      <webElementGuid>9b37037d-4ee5-4a6f-9704-7cd4d1f5d483</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
