<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cookie-instellingen</name>
   <tag></tag>
   <elementGuidId>0bdebf13-a400-4375-8a33-e52799c571f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='onetrust-pc-btn-handler']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#onetrust-pc-btn-handler</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bfbba135-8b01-42ef-ba96-86618a66537d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>onetrust-pc-btn-handler</value>
      <webElementGuid>9267d5db-09c9-4c60-abfe-4e8a54ddcc73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cookie-setting-link</value>
      <webElementGuid>4a5cafc0-ebe0-4ce4-90e6-9b360cd99310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cookie-instellingen</value>
      <webElementGuid>70a96045-370b-442a-9dc7-ed549d3cb770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;onetrust-pc-btn-handler&quot;)</value>
      <webElementGuid>fbbbc02f-8179-4c10-8c09-4295c903f698</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='onetrust-pc-btn-handler']</value>
      <webElementGuid>6729f461-c91f-4b88-b864-c5bda4e1cc66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='onetrust-button-group']/button</value>
      <webElementGuid>48c6d2ab-f7a1-4b7f-8eb6-752544729fe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mijn keuzes bevestigen'])[1]/following::button[1]</value>
      <webElementGuid>d0166ea5-4e9f-4bd9-bf43-df926d36e649</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='label'])[4]/following::button[2]</value>
      <webElementGuid>2d99a42e-b074-404b-b3ec-2dfab5a6df8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alle cookies accepteren'])[1]/preceding::button[1]</value>
      <webElementGuid>afd05464-9e53-4bdb-83c5-7c857da51917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cookie-instellingen']/parent::*</value>
      <webElementGuid>5f4ce8df-efe7-4754-af84-4812e1e68fe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/button</value>
      <webElementGuid>4018e6aa-759a-4e0b-8df1-0ab1d5a8d710</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'onetrust-pc-btn-handler' and (text() = 'Cookie-instellingen' or . = 'Cookie-instellingen')]</value>
      <webElementGuid>66ec3bd9-3a32-4d01-85b2-64f8c78c393b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
