<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_F R A N K Y</name>
   <tag></tag>
   <elementGuidId>ba7af9c5-bb8d-4471-99e8-9a4fcb8bbf7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.RPtvS</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ad593566-6371-4843-845e-6420c4adc458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e3c15c41-4a7b-4b45-9188-2f596dda2177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Selecteer het profiel: F R A N K Y</value>
      <webElementGuid>e774e583-c0df-4cac-8c03-bc7e7d69393d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>RPtvS</value>
      <webElementGuid>f3326716-93bd-4f8c-b0b1-826466d54ae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>F R A N K Y</value>
      <webElementGuid>82ecc139-aeb8-4b53-bd9f-644f8ea97d3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[1]/section[@class=&quot;n7wtA&quot;]/ul[@class=&quot;_2kY8F&quot;]/li[1]/button[@class=&quot;RPtvS&quot;]</value>
      <webElementGuid>eb66cbee-72f6-4ab0-bf96-c791466dd8b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>55f72051-05fe-4683-9df7-96c76835b969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/section/ul/li/button</value>
      <webElementGuid>f0644a80-011a-4b60-928a-84985c7280bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wie gaat er kijken?'])[1]/following::button[1]</value>
      <webElementGuid>453c720b-dcb8-4111-afa9-c8773f3bb3bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lees hier welke browsers er worden ondersteund'])[1]/following::button[1]</value>
      <webElementGuid>1e69ae54-6bf6-4aa3-9923-191c06cb7085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Algemene voorwaarden'])[1]/preceding::button[5]</value>
      <webElementGuid>ebdd13b1-9a51-4e3f-ace8-5311d004c70a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy &amp; cookies'])[1]/preceding::button[5]</value>
      <webElementGuid>fbf80a6c-5d90-47fa-8f23-1a26ed915737</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>c175b1f9-d870-4172-847c-8360a096d3d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'F R A N K Y' or . = 'F R A N K Y')]</value>
      <webElementGuid>474bcb20-313c-404f-abad-63c3b1f0aa98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
