<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Mijn series - Top Menu</name>
   <tag></tag>
   <elementGuidId>c570167c-6333-4035-9008-5bcb8b21eded</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/header/nav/ul/li[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3388c051-f89d-467a-a63f-da3378ab31fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ADZ5z</value>
      <webElementGuid>69abe53c-7443-4e2e-b538-b6bbbc4f923a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/mijn-series</value>
      <webElementGuid>a95bc02f-f37d-486b-b0a5-f4f4e6b54af4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mijn series</value>
      <webElementGuid>4edf41c1-3b35-4fe5-a135-af3eea12428d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;_6ZAPB&quot;]/header[@class=&quot;ztPjg&quot;]/nav[@class=&quot;BpvhZ N6qwo&quot;]/ul[@class=&quot;VdiiA&quot;]/li[@class=&quot;iMTCz&quot;]/a[@class=&quot;ADZ5z&quot;]</value>
      <webElementGuid>c0d988b1-9c1e-48e3-b6d9-303ef7362846</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/header/nav/ul/li[4]/a</value>
      <webElementGuid>a19ad189-5962-490b-83fe-b60281c7429a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Mijn series')]</value>
      <webElementGuid>f3874b9a-d7da-4d05-a658-73497a596017</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kijk later'])[1]/following::a[1]</value>
      <webElementGuid>431ae2c7-29da-47fb-b9ce-705963dd4563</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tv &amp; gids'])[1]/following::a[2]</value>
      <webElementGuid>2077527f-c2f7-4b48-8655-d5b429bae7ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[2]/preceding::a[2]</value>
      <webElementGuid>fb5188e4-d136-49de-9233-5d40557a6ce6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tv &amp; gids'])[2]/preceding::a[3]</value>
      <webElementGuid>d0664031-aa6a-4010-a5d9-461a58432a33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mijn series']/parent::*</value>
      <webElementGuid>278de39e-e1f0-4387-b0ea-9797997debdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/mijn-series')]</value>
      <webElementGuid>f7b1f994-e020-47ed-b193-8c3ce04e9205</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>1812add2-a1ba-491b-90b7-d5b81e83b82c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/mijn-series' and (text() = 'Mijn series' or . = 'Mijn series')]</value>
      <webElementGuid>340d1304-e7f6-40fb-b02c-4abacb6f0f00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
