<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NPO Logo</name>
   <tag></tag>
   <elementGuidId>eae1c50f-3e71-4c12-b4e7-060729f4c6dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.loky3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/main/div/section[2]/ul/li/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>da626bad-acd0-4bd7-80bb-509ce072223b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>loky3</value>
      <webElementGuid>e8c74c5b-d0a1-45a6-bf6b-a25ae65b6ea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://images.nlziet.nl//static/assets/contentproviders/flat/npo.svg</value>
      <webElementGuid>71c00618-5b53-48e5-b9c0-ac05709d4532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>npo</value>
      <webElementGuid>a36d53da-f31d-478c-af9b-f92fa5c178ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;oKpQ7&quot;]/main[1]/div[@class=&quot;ze9C9 NCnyv&quot;]/section[@class=&quot;_0eIXV&quot;]/ul[@class=&quot;H72Ol&quot;]/li[@class=&quot;_4lOiO&quot;]/a[@class=&quot;P9fEf&quot;]/img[@class=&quot;loky3&quot;]</value>
      <webElementGuid>7105daa0-4779-4b6c-b792-e9684c0cc998</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/section[2]/ul/li/a/img</value>
      <webElementGuid>54e27774-3434-4be6-bb5d-7917497fa05e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='npo']</value>
      <webElementGuid>1a823b7f-1f2a-4482-aeb1-48e03b208ed8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>c75e6c32-7ae2-464c-a54f-d060b91c421d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://images.nlziet.nl//static/assets/contentproviders/flat/npo.svg' and @alt = 'npo']</value>
      <webElementGuid>64e1951b-9ec9-43b4-8618-7e9cdfd38f11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
