<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Log in om programmas te kijken</name>
   <tag></tag>
   <elementGuidId>53757e00-621b-4593-9765-baba3049ca84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.PS3ci</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='popup']/ul/div/li/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>6c8b72da-bbc5-41ed-88a2-a78182536bbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4c8645d0-1909-4c31-9f2a-46ec0fb6e5d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PS3ci</value>
      <webElementGuid>c5b8a576-2ca6-4e96-9202-e18e4a993e21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log in om programma's te kijken.</value>
      <webElementGuid>a2a78114-5d8c-48ee-9da0-d9e422d8b77e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popup&quot;)/ul[@class=&quot;vl5vp WB-Qk&quot;]/div[@class=&quot;kywGF&quot;]/li[@class=&quot;_6n7hr&quot;]/p[@class=&quot;PS3ci&quot;]</value>
      <webElementGuid>403c29e9-0944-4ff7-991f-d9f652ba055e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>a2c99827-00bb-4249-8e9e-62133bc72175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ab87211f-db74-42f9-a9c4-9297e9c46c82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PS3ci</value>
      <webElementGuid>816e420c-87fb-4f10-8301-56104cc4b892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log in om programma's te kijken.</value>
      <webElementGuid>e213b19a-5856-4b44-86df-c3cfab597b8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popup&quot;)/ul[@class=&quot;vl5vp WB-Qk&quot;]/div[@class=&quot;kywGF&quot;]/li[@class=&quot;_6n7hr&quot;]/p[@class=&quot;PS3ci&quot;]</value>
      <webElementGuid>ba3f9b47-254c-4616-a166-de92d33c4bba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popup']/ul/div/li/p</value>
      <webElementGuid>5c80de20-c1d2-46ed-9551-d2e28bc475a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lees hier welke browsers er worden ondersteund'])[1]/following::p[1]</value>
      <webElementGuid>c974dc33-0de6-4f10-8e38-8104d172396c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Je browser wordt helaas niet meer ondersteund.'])[1]/following::p[2]</value>
      <webElementGuid>c936060d-2e0e-4485-8e60-611a0a18d377</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nog geen account? Meld je aan.'])[1]/preceding::p[1]</value>
      <webElementGuid>4ef85f0e-6dc3-42c1-8d81-2675af53d1a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inloggen'])[1]/preceding::p[1]</value>
      <webElementGuid>09fd58b4-bb0e-48b9-96a1-b6e4aa7cb1b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/p</value>
      <webElementGuid>91eef353-7497-416e-933c-de6f1fea88aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = concat(&quot;Log in om programma&quot; , &quot;'&quot; , &quot;s te kijken.&quot;) or . = concat(&quot;Log in om programma&quot; , &quot;'&quot; , &quot;s te kijken.&quot;))]</value>
      <webElementGuid>02ddfbbc-7951-488b-bc6c-e97f9f7b94cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
