<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_NOS Journaal_L71ZH</name>
   <tag></tag>
   <elementGuidId>8033d824-67bf-474a-9df7-0d8ab31a0afa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='NOS Journaal'])[2]/following::*[name()='svg'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>ac3a0300-c990-4767-bf4d-ec7fd985197a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>18dd51b3-68e2-433b-8e31-de13987b7c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>f1156614-af8d-4087-89f6-7d47a9014cb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>6663d659-ece9-4a3a-9db3-e037486af348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>47d67c74-d8d7-405f-9dc8-59079948800d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>84def4bb-bcea-48b9-b793-2bb8f294cb78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>L71ZH</value>
      <webElementGuid>635b28cd-5b7e-4df4-b6c4-c5e98953b754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;oKpQ7&quot;]/main[@class=&quot;_5CuVX&quot;]/div[@class=&quot;jk3Gn&quot;]/header[@class=&quot;RPZ7L yrqsB&quot;]/button[@class=&quot;J9be6&quot;]/svg[@class=&quot;L71ZH&quot;]</value>
      <webElementGuid>c9ea22d4-807b-4237-a41e-778f74350db6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NOS Journaal'])[2]/following::*[name()='svg'][1]</value>
      <webElementGuid>31c0c78c-ca9a-4baa-8d5b-c84e1954db67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NOS Journaal'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>b7dec838-a0a5-4611-aaba-fa9e9bb6890d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NOS Journaal'])[3]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>830dcb37-d5fb-4e9b-a4a9-74945fa6c52f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oppassen!!!'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>a376bda9-cdd9-41c6-9cf0-86f29b9e9ff3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
