<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Afspelen</name>
   <tag></tag>
   <elementGuidId>0e376e8c-1f5a-495b-9653-9b9695ddfe4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.Txy9a.GFS-s</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9088406e-ad83-4d47-872d-684c39b07c44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Afspelen</value>
      <webElementGuid>b9acfdc0-c925-4ea3-8b30-75e412f72af0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>103e12b8-fe50-4b53-9033-2ab34d5b2780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Txy9a GFS-s</value>
      <webElementGuid>876dec2e-ea43-46f3-ad28-90c883ec28bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a8ff5cb4-7fe5-4704-a984-8c13fc5ae720</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Afspelen</value>
      <webElementGuid>1554ba5f-7453-4376-97d5-688d6d03145b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;oKpQ7&quot;]/main[@class=&quot;ffEFH&quot;]/div[@class=&quot;DHp71&quot;]/div[@class=&quot;POGle&quot;]/button[@class=&quot;Txy9a GFS-s&quot;]</value>
      <webElementGuid>bd4f6f53-7ad9-43b9-9643-6c068bd56d6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>379b6bbe-951f-4e77-a340-512c0e2a2a4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div[2]/button</value>
      <webElementGuid>fc065ef2-ddeb-4256-be4f-7ab102807a20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vandaag Inside'])[1]/following::button[1]</value>
      <webElementGuid>04b1e4eb-5b76-4289-9825-5a2b60ba8824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mijn series'])[2]/following::button[1]</value>
      <webElementGuid>49bf8355-e644-4bbf-86a0-7a046efee758</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mijn series'])[3]/preceding::button[1]</value>
      <webElementGuid>57e357da-4d5f-42e5-9539-c0b23c9753b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Afspelen']/parent::*</value>
      <webElementGuid>66c9967f-5310-48e9-8271-f0ab24e2d207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/button</value>
      <webElementGuid>97f1d19a-c7b3-427f-a148-ca00aa49d6ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Afspelen' or . = 'Afspelen')]</value>
      <webElementGuid>2eb1785b-2632-4b5b-bbf3-bed8e4419d95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
