<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Informatief</name>
   <tag></tag>
   <elementGuidId>7276e643-ad6e-47be-98ae-9b0572b80609</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal']/div/section/div/section/div[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.JyQbB</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>68aa8e4f-2f17-437a-9836-9e69ba5e338a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>JyQbB</value>
      <webElementGuid>c485a06d-174f-483e-9885-399e12763ce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Informatief</value>
      <webElementGuid>8e8457db-7ed2-4156-824f-f5732de5251c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal&quot;)/div[@class=&quot;Yj-98&quot;]/section[@class=&quot;gYjx2&quot;]/div[@class=&quot;q6v9P&quot;]/section[1]/div[@class=&quot;JyQbB&quot;]</value>
      <webElementGuid>50c3b2ef-e1ab-459e-8ba1-ccb64b6f91aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal']/div/section/div/section/div[4]</value>
      <webElementGuid>e0ca33db-9eed-409e-9ea3-6c406b0ba884</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zendtijd voor politieke partijen in Nederland.'])[1]/following::div[1]</value>
      <webElementGuid>820fba7b-9d7a-4a9c-aa11-9ba0f8edcca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kijk later'])[1]/following::div[2]</value>
      <webElementGuid>a0d9dbf7-2371-4422-af90-ab569f8f8d05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Politieke Partijen'])[2]/preceding::div[2]</value>
      <webElementGuid>a8dee389-d0c4-432a-a397-b67efab48ffd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div[4]</value>
      <webElementGuid>3f79547f-c83a-4e4a-bba9-b4ef30d5a7df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Informatief' or . = 'Informatief')]</value>
      <webElementGuid>8d41dd83-796f-4682-8cfc-7f643b181969</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
