<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1754</name>
   <tag></tag>
   <elementGuidId>bfcee3f6-35bc-431b-b6ed-37d31fe6ea82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(starts-with(text(), '1') or starts-with(., '1'))]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/main/div/div/ul/li/div[2]/ul/li[60]/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.lDeqJ.r12g6.ir1Sx > div.vPJpI > div.Hk7SS</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3a1ff17f-ed2f-4503-9044-e4d877d10d8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Hk7SS</value>
      <webElementGuid>2ac56cad-878c-4961-b4e4-7a6a6eff1ee0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>starts with</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>1876a2ea-01b3-4e4e-8821-0541c9f78e25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;oKpQ7&quot;]/main[1]/div[@class=&quot;RK2ul&quot;]/div[@class=&quot;dCx4m&quot;]/ul[@class=&quot;_1fJOR&quot;]/li[1]/div[@class=&quot;Kfn4-&quot;]/ul[@class=&quot;dzwVg&quot;]/li[60]/div[@class=&quot;lDeqJ r12g6 ir1Sx&quot;]/div[@class=&quot;vPJpI&quot;]/div[@class=&quot;Hk7SS&quot;]</value>
      <webElementGuid>b25d8536-f7d1-4893-9606-42b7536bcfab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div/ul/li/div[2]/ul/li[60]/div/div/div</value>
      <webElementGuid>f283fe23-99d5-4c1e-8c4a-ba5555c2e7dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tijd voor MAX'])[2]/following::div[3]</value>
      <webElementGuid>1415dc3a-04bd-403b-9db8-6a0c5309cec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NOS Journaal'])[38]/following::div[8]</value>
      <webElementGuid>e53aed37-762a-4714-b5c1-0a882d464bb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Politieke Partijen: 50PLUS'])[1]/preceding::div[1]</value>
      <webElementGuid>7b35dd2e-f72a-451a-9e46-646f0f3112ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Politieke Partijen: JA21'])[1]/preceding::div[4]</value>
      <webElementGuid>9cc12067-c75a-4b41-a136-0cbee4d5ac82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='17:54']/parent::*</value>
      <webElementGuid>52f36b11-10d9-4979-9cc6-9629d5d00f65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[60]/div/div/div</value>
      <webElementGuid>f82c0730-a242-4dfa-8fca-48948a72dba5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '17:54' or . = '17:54')]</value>
      <webElementGuid>9dc19d40-4740-4c16-a9f4-0a3ac79523bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
