<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dropdown - NPO 1</name>
   <tag></tag>
   <elementGuidId>d5514071-7e39-4fdd-b62c-ea71b96da890</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/main/div/nav/div[4]/div/div[2]/div/span/button/div/p/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span > button.ncw4h > div.G7jhL > p._2-VvZ > span.fNXpq</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6fdb837a-7cc6-4c23-a1f5-84b29a8ebe50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fNXpq</value>
      <webElementGuid>8e809f60-a3f8-4535-96ce-11a5ed319297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NPO 1</value>
      <webElementGuid>dbcb97c7-a29b-4586-8b4b-328cd06a1325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;oKpQ7&quot;]/main[1]/div[@class=&quot;RK2ul&quot;]/nav[@class=&quot;LS3wy&quot;]/div[@class=&quot;JTPbn&quot;]/div[@class=&quot;_0nfEU&quot;]/div[@class=&quot;D6fTg&quot;]/div[@class=&quot;B77d0&quot;]/span[1]/button[@class=&quot;ncw4h&quot;]/div[@class=&quot;G7jhL&quot;]/p[@class=&quot;_2-VvZ&quot;]/span[@class=&quot;fNXpq&quot;]</value>
      <webElementGuid>e0f8e3d8-5855-4093-8049-40a290c3004f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/nav/div[4]/div/div[2]/div/span/button/div/p/span</value>
      <webElementGuid>a21cc03b-2e1b-434c-8711-5291abac6bde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NPO 1'])[1]/following::span[3]</value>
      <webElementGuid>3c176f89-ca50-4d74-892a-12bc4578bcf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Primetime'])[1]/following::span[4]</value>
      <webElementGuid>4c774bdd-5ea0-43a7-9288-3f6ab8997e96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NPO 2'])[1]/preceding::span[1]</value>
      <webElementGuid>bb25761c-3b5d-4a83-878c-9d432af0fe76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NPO 3'])[1]/preceding::span[2]</value>
      <webElementGuid>eac6b827-8a0d-4c64-8249-b21c0cba6102</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/button/div/p/span</value>
      <webElementGuid>b0cf5a9b-9ce3-4905-8208-6c2866d8a907</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'NPO 1' or . = 'NPO 1')]</value>
      <webElementGuid>cefb1019-fc9b-46ff-af63-1931e898abea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
