<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dropdown - NPO 1</name>
   <tag></tag>
   <elementGuidId>d5514071-7e39-4fdd-b62c-ea71b96da890</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/main/div/nav/div[4]/div/div[2]/div/span/button/div/p/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span > button.ncw4h > div.G7jhL > p._2-VvZ > span.fNXpq</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a7199214-6602-4f52-8de5-e55cd863f338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fNXpq</value>
      <webElementGuid>dbe4c66c-2c8d-4ef9-b36a-c46a17654099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NPO 1</value>
      <webElementGuid>6d8d3f14-8a70-430d-847c-28225799b371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;oKpQ7&quot;]/main[1]/div[@class=&quot;RK2ul&quot;]/nav[@class=&quot;LS3wy&quot;]/div[@class=&quot;JTPbn&quot;]/div[@class=&quot;_0nfEU&quot;]/div[@class=&quot;D6fTg&quot;]/div[@class=&quot;B77d0&quot;]/span[1]/button[@class=&quot;ncw4h&quot;]/div[@class=&quot;G7jhL&quot;]/p[@class=&quot;_2-VvZ&quot;]/span[@class=&quot;fNXpq&quot;]</value>
      <webElementGuid>4b5ef9e2-6dec-4db9-bf14-1a7be958f504</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/nav/div[4]/div/div[2]/div/span/button/div/p/span</value>
      <webElementGuid>fb04a26e-9650-45fe-acf6-74fb7e92cff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NPO 1'])[1]/following::span[3]</value>
      <webElementGuid>782d99f6-b58f-4b53-9a75-445dcbd44307</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Primetime'])[1]/following::span[4]</value>
      <webElementGuid>bb9eebbc-bb7d-4772-a279-22c727726dd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NPO 2'])[1]/preceding::span[1]</value>
      <webElementGuid>b3ffb4d4-c604-413f-a5fb-deb10e8b7dc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NPO 3'])[1]/preceding::span[2]</value>
      <webElementGuid>3cf92dc3-32e5-49cf-ba3b-7c6e0b5dd705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/button/div/p/span</value>
      <webElementGuid>bdcbcebf-3bb3-4aca-aec2-41838e3433ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'NPO 1' or . = 'NPO 1')]</value>
      <webElementGuid>db8ccb36-5cb5-48b4-a3e3-b6e3b982fad8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
