<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dropdown kanalen kiezer</name>
   <tag></tag>
   <elementGuidId>3e4e0feb-f53d-4cda-9a66-80d13b9ebbaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/main/div/nav/div[4]/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.JTPbn > div._0nfEU > div.Ws6ad > span.Cfqky</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b45f2884-784f-4277-9201-b92dc8f905a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Cfqky</value>
      <webElementGuid>7b6dcd30-c113-468c-b206-09d9d6300f1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;oKpQ7&quot;]/main[1]/div[@class=&quot;RK2ul&quot;]/nav[@class=&quot;LS3wy&quot;]/div[@class=&quot;JTPbn&quot;]/div[@class=&quot;_0nfEU&quot;]/div[@class=&quot;Ws6ad&quot;]/span[@class=&quot;Cfqky&quot;]</value>
      <webElementGuid>155eb565-22e7-422f-b494-fa9e940ebe85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/nav/div[4]/div/div/span</value>
      <webElementGuid>fdd09094-e056-49de-8aad-7d6718bb68b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/span</value>
      <webElementGuid>cdd53084-35f0-4ae4-966c-5e364f9846b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
