<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Logo RTV Utrecht</name>
   <tag></tag>
   <elementGuidId>b21f72bd-27ae-4acf-862d-59bad861561a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/main/div/div/ul/li[42]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e78d7390-6e68-4ccb-8a04-723fa9d8cdaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>R1KLd</value>
      <webElementGuid>9948b465-281c-468f-bf1d-1254b6fd62ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn.nlziet.nl/static/assets/channels/rtvutrecht.png</value>
      <webElementGuid>3b47ee2e-46a4-4607-aaba-939937bdd730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>RTV Utrecht</value>
      <webElementGuid>d199504c-8af1-496b-9bcc-a514f074bd5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>RTV Utrecht</value>
      <webElementGuid>4f16f9a1-613d-4e9a-8ab4-4c952186f728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;oKpQ7&quot;]/main[1]/div[@class=&quot;RK2ul&quot;]/div[@class=&quot;dCx4m&quot;]/ul[@class=&quot;_1fJOR&quot;]/li[42]/div[@class=&quot;WfofP&quot;]/div[@class=&quot;yNHua&quot;]/img[@class=&quot;R1KLd&quot;]</value>
      <webElementGuid>8b59c429-c9c9-41de-b08d-28de136dc0d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div/ul/li[42]/div/div/img</value>
      <webElementGuid>307655c4-b9e8-40fa-829e-487cbc628624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='RTV Utrecht']</value>
      <webElementGuid>9db1ad79-8817-44e4-8090-1373bbdad7db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[42]/div/div/img</value>
      <webElementGuid>9c81d7cf-1a6f-4d67-bfb3-7db8fbe63db4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdn.nlziet.nl/static/assets/channels/rtvutrecht.png' and @title = 'RTV Utrecht' and @alt = 'RTV Utrecht']</value>
      <webElementGuid>ea51e33d-931c-43c7-953f-4dd40e936398</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
