<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Logo AT5</name>
   <tag></tag>
   <elementGuidId>ab28b0ed-b1b3-415c-a7c5-e2a411fc16a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/main/div/div/ul/li[48]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b9a29ffa-99d8-4bb3-a62e-bd3fec3f70d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>R1KLd</value>
      <webElementGuid>0f366364-3021-4858-b77b-641cb6fdf00f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn.nlziet.nl/static/assets/channels/at5.png</value>
      <webElementGuid>e706a84f-d1dc-4f1c-bfc0-62333c8cead7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>AT5</value>
      <webElementGuid>f7622747-0597-4d2a-84d8-30cfc2c029fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>AT5</value>
      <webElementGuid>87fbb887-610c-40ea-90da-1109cf061fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;oKpQ7&quot;]/main[1]/div[@class=&quot;RK2ul&quot;]/div[@class=&quot;dCx4m&quot;]/ul[@class=&quot;_1fJOR&quot;]/li[48]/div[@class=&quot;WfofP&quot;]/div[@class=&quot;yNHua&quot;]/img[@class=&quot;R1KLd&quot;]</value>
      <webElementGuid>a2dbe8fc-3d57-4cda-a55d-ffb82caebcd8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div/ul/li[48]/div/div/img</value>
      <webElementGuid>8c295f74-ecee-4b80-b986-f28f9acf2b94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='AT5']</value>
      <webElementGuid>266f1f67-bec5-4f36-9a17-801ec1e3aac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[48]/div/div/img</value>
      <webElementGuid>d58e4e43-95a2-475d-9e0d-82ed82db2723</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdn.nlziet.nl/static/assets/channels/at5.png' and @title = 'AT5' and @alt = 'AT5']</value>
      <webElementGuid>2b797e8d-90a5-4611-8124-09986360ebc6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
