<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Logo Omroep Gelderland</name>
   <tag></tag>
   <elementGuidId>ead54bb7-0120-44b6-87f9-4c9d602ba1f8</elementGuidId>
   <imagePath>Screenshots/Targets/Object Repository/Page_NLZIET  Tv  gids/Logo Omroep Gelderland.png</imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Object Repository/Page_NLZIET  Tv  gids/Logo Omroep Gelderland.png</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>c</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>70555bb6-135c-4261-bcb3-c3d492521cc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>R1KLd</value>
      <webElementGuid>fc6a4548-cb1a-44da-a0f5-dbd138e7d925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn.nlziet.nl/static/assets/channels/tvgelderland.png</value>
      <webElementGuid>7dbe0d65-0675-4cef-a2da-d0727a827ecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>TV Gelderland</value>
      <webElementGuid>4d7f02f5-be76-4c93-9b39-b0a1eafff259</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>TV Gelderland</value>
      <webElementGuid>29476269-5af3-48e7-8cdb-65d9e3bb755a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;oKpQ7&quot;]/main[1]/div[@class=&quot;RK2ul&quot;]/div[@class=&quot;dCx4m&quot;]/ul[@class=&quot;_1fJOR&quot;]/li[39]/div[@class=&quot;WfofP&quot;]/div[@class=&quot;yNHua&quot;]/img[@class=&quot;R1KLd&quot;]</value>
      <webElementGuid>e3594013-f2f2-443c-80aa-3228f3a478a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div/ul/li[39]/div/div/img</value>
      <webElementGuid>7413c4d0-0c59-4500-9857-2a0fe2241969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='TV Gelderland']</value>
      <webElementGuid>4fcfd29f-4697-4fa1-9328-f1c50b999a13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[39]/div/div/img</value>
      <webElementGuid>60f07682-6c92-4711-ae42-e767c4ef1530</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdn.nlziet.nl/static/assets/channels/tvgelderland.png' and @title = 'TV Gelderland' and @alt = 'TV Gelderland']</value>
      <webElementGuid>479c24e3-98c1-4d4a-850a-df53658e4792</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
