<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Omschrijving programma</name>
   <tag></tag>
   <elementGuidId>c4c4bc51-3bd3-4cc8-a786-d339b82c0396</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal']/div/section/div/section/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.B77d0.Xf5FY</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>186c5504-4527-4a89-b855-a17490e964d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9407fdf6-9f8b-4a7d-bf6d-db67285dacd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Omschrijving</value>
      <webElementGuid>9b0cf46c-9018-4e68-9936-6a3f625f2f5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>content-qYN5x_uuSEeDs44eA2JAkQ</value>
      <webElementGuid>9e5e982b-73bd-4f87-b68c-91420a561b73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>B77d0 Xf5FY</value>
      <webElementGuid>f155db34-b598-4033-acaa-285549e6ec61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Zendtijd voor politieke partijen in Nederland.</value>
      <webElementGuid>9c805e3c-445f-412e-a980-a5ee0aa3d396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal&quot;)/div[@class=&quot;Yj-98&quot;]/section[@class=&quot;gYjx2&quot;]/div[@class=&quot;q6v9P&quot;]/section[1]/div[@class=&quot;B77d0 Xf5FY&quot;]</value>
      <webElementGuid>b150b5d5-8a75-4624-89f6-693577b477c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal']/div/section/div/section/div[3]</value>
      <webElementGuid>3e4adcc4-e44c-4ff6-b7ff-42326dd4d6f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kijk later'])[1]/following::div[1]</value>
      <webElementGuid>825cda5b-647c-4e13-b5cb-38259c000941</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Politieke Partijen'])[1]/following::div[6]</value>
      <webElementGuid>fa5f7bdb-8626-4b32-b3b5-511906ffa0b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informatief'])[1]/preceding::div[1]</value>
      <webElementGuid>8db227b0-7507-434d-8801-dd8b8cb173c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div[3]</value>
      <webElementGuid>bf15b324-0c7e-404a-8351-300d97077f6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Zendtijd voor politieke partijen in Nederland.' or . = 'Zendtijd voor politieke partijen in Nederland.')]</value>
      <webElementGuid>32ff3f6d-7908-4cd6-ba78-66e331810bc8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
