<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_NPO 1</name>
   <tag></tag>
   <elementGuidId>e40b7ee7-6949-4464-9a7b-ae4ab9b4affa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/main/div/nav/div[4]/div/div[2]/div/span/button/div/p/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span > button.ncw4h > div.G7jhL > p._2-VvZ > span.fNXpq</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b4ae3671-a3bd-4d85-aae0-9f3b20f97eb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fNXpq</value>
      <webElementGuid>31507384-674d-4fd1-af6c-e3848bd46787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NPO 1</value>
      <webElementGuid>6fef3a79-8765-4e77-8933-d087654c44f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;oKpQ7&quot;]/main[1]/div[@class=&quot;RK2ul&quot;]/nav[@class=&quot;LS3wy&quot;]/div[@class=&quot;JTPbn&quot;]/div[@class=&quot;_0nfEU&quot;]/div[@class=&quot;D6fTg&quot;]/div[@class=&quot;B77d0&quot;]/span[1]/button[@class=&quot;ncw4h&quot;]/div[@class=&quot;G7jhL&quot;]/p[@class=&quot;_2-VvZ&quot;]/span[@class=&quot;fNXpq&quot;]</value>
      <webElementGuid>f3d7d1df-ee7f-4131-89f0-1aabb16e8465</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/nav/div[4]/div/div[2]/div/span/button/div/p/span</value>
      <webElementGuid>9bc7862e-103f-4a29-be1c-34ae6f439bf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NPO 1'])[1]/following::span[3]</value>
      <webElementGuid>89eff778-e3be-4ac5-9680-bd4382ceffc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Primetime'])[1]/following::span[4]</value>
      <webElementGuid>5ce42d38-6791-4f9f-b145-b8611b564de0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NPO 2'])[1]/preceding::span[1]</value>
      <webElementGuid>8ac61a9d-3021-48ba-b0e4-5516c51fdebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NPO 3'])[1]/preceding::span[2]</value>
      <webElementGuid>d8c50a70-7810-4d72-be93-8c8abd7e30f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/button/div/p/span</value>
      <webElementGuid>c3402f55-3f98-445a-b114-b006af6eb12a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'NPO 1' or . = 'NPO 1')]</value>
      <webElementGuid>f179346b-3b8b-40b1-921c-e8e14396c89f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
