<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Inloggen</name>
   <tag></tag>
   <elementGuidId>5277b656-d9e0-485c-83bc-3caad929dde0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;button&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3ce302bd-b45b-46ff-ba45-3004400be209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>a5e5493a-39ff-4f76-a87e-5135df2e3823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f5f65eef-7c67-4f33-8949-026b29fe70d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>login</value>
      <webElementGuid>5a91342e-73b5-4ab6-a0a8-5aa345324b67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Inloggen</value>
      <webElementGuid>7d071146-99d1-444f-b5c9-35fd6752c391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;primary-container&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6&quot;]/form[1]/div[@class=&quot;form-group&quot;]/button[@class=&quot;btn btn-primary&quot;]</value>
      <webElementGuid>17fc0c26-e62c-4c73-a87d-d601d0ad7129</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='button']</value>
      <webElementGuid>080cfa23-800d-4aa0-9612-714b2b5860e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='primary-container']/div/div/form/div[4]/button</value>
      <webElementGuid>c2b0838c-930f-480a-88cb-00be9509c1f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ingelogd blijven'])[1]/following::button[1]</value>
      <webElementGuid>afbb0355-769f-4b6d-9f64-7f7f9cb26333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wachtwoord'])[1]/following::button[1]</value>
      <webElementGuid>dfaca82f-ae70-4d69-93a2-bcf4f9d9f3d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wachtwoord vergeten'])[1]/preceding::button[1]</value>
      <webElementGuid>d0be98ff-bd8d-434c-b55d-caf1719ed7c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>4dd9dcce-23c2-4606-91f7-091482460d17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'button' and (text() = 'Inloggen' or . = 'Inloggen')]</value>
      <webElementGuid>27acf6ad-f789-445e-a4d8-fbb733efdec1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
