<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_Er is een fout in het formulier</name>
   <tag></tag>
   <elementGuidId>a6cdb60b-ba94-4769-9e6d-9ac808082a58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>strong</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='primary-container']/div/strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>bee21c73-0770-4d7c-b59c-630aabcada96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Er is een fout in het formulier</value>
      <webElementGuid>47e0700f-65e3-4a5b-bcf6-2f3da8b6871f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;primary-container&quot;)/div[@class=&quot;alert alert-danger&quot;]/strong[1]</value>
      <webElementGuid>f3521c79-113a-4381-bd82-454cb856aa83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>2cc9e3b8-f40d-48d7-a494-8cd22566135b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Er is een fout in het formulier</value>
      <webElementGuid>76fee79e-7454-48e6-87a0-9ae412d3dc75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;primary-container&quot;)/div[@class=&quot;alert alert-danger&quot;]/strong[1]</value>
      <webElementGuid>1e7a1751-e4c7-40ec-89c3-0174415e99dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='primary-container']/div/strong</value>
      <webElementGuid>83acb9d8-1b06-4ba8-b790-1e35c601d5ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inloggen'])[1]/following::strong[1]</value>
      <webElementGuid>2b1c960f-15e5-476b-982c-8128d1caccd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ongeldige e-mailadres of wachtwoord'])[1]/preceding::strong[1]</value>
      <webElementGuid>12afbbc0-ceeb-448b-ac6b-74ffdfe4f0ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E-mailadres'])[1]/preceding::strong[1]</value>
      <webElementGuid>2b1dae6b-9400-40d8-8bb6-a8ebcb3ae321</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Er is een fout in het formulier']/parent::*</value>
      <webElementGuid>e00b20ff-9b96-418c-b6b4-e28d804685da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//strong</value>
      <webElementGuid>819f00a6-99eb-48b8-a40b-4afb0d967f9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = 'Er is een fout in het formulier' or . = 'Er is een fout in het formulier')]</value>
      <webElementGuid>5f3b70a6-ccbf-4c41-a797-df9a41b7705c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
